---
sidebar: sidebar 
permalink: concept_lic_platforms.html 
keywords: license, licensing, platform license offerings, license offerings, standard, premium, premium xl 
summary: 'Vous pouvez acheter une licence ONTAP Select Capacity Tier ou Capacity Pool dans l"un des trois niveaux de capacité de plateforme. Ces offres de licence déterminent les capacités des hôtes sur lesquels vous déployez ONTAP Select.' 
---
= Découvrez les offres de licences de plateforme pour ONTAP Select
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Vous pouvez acheter une licence ONTAP Select Capacity Tier ou Capacity Pool aux niveaux standard, premium ou premium XL. Ces offres de licence déterminent les capacités des hôtes sur lesquels vous déployez ONTAP Select.



== Ce qu'offre une offre de licence de plateforme

Une offre de licence spécifique détermine les capacités de l'hôte hyperviseur dans deux domaines :

* Type d'instance (CPU, mémoire)
* Fonctionnalités supplémentaires


Les offres de licences sont classées par ordre croissant de fonctionnalités, de la version standard à la version premium XL. En général, l'option de licence que vous choisissez vous accorde les fonctionnalités de ce niveau ainsi que de tous les niveaux inférieurs. Par exemple, le niveau premium fournit les fonctionnalités des niveaux premium et standard.

Le tableau suivant compare les fonctionnalités des licences standard, premium et premium XL.

[cols="25,25,25,25,25"]
|===
2+| La licence prend en charge... | Standard | Premium | XL haut de gamme 


2+| Type d'instance | Petit seulement | Petit ou moyen | Petit, moyen ou grand 


.2+| Disques durs (HDD) dans un ... | Configuration RAID matérielle | Oui | Oui | Oui 


| configuration vNAS | Oui | Oui | Oui 


.3+| Les disques SSD (Solid State Drives) dans un ... | Configuration RAID matérielle | Non | Oui | Oui 


| Configuration RAID logicielle | Non | Oui | Oui 


| configuration vNAS | Oui | Oui | Oui 


.3+| Les disques NVMe dans un ... | Configuration RAID matérielle | Non | Non | Oui 


| Configuration RAID logicielle | Non | Non | Oui 


| configuration vNAS | Oui | Oui | Oui 


2+| MetroCluster SDS | Non | Oui | Oui 
|===

NOTE: Les machines virtuelles basées sur le noyau (KVM) ne prennent pas en charge le type d'instance large.



== Comparer la prise en charge matérielle des offres de licences de plateforme

Les licences standard, premium et premium XL sont compatibles avec une large gamme de matériels et de logiciels. Pour des informations à jour sur les versions matérielles et logicielles, consultez le link:https://mysupport.netapp.com/matrix/["Outil Interoperability Matrix Tool"^].

[role="tabbed-block"]
====
.Élément principal
--
[cols="5"30"]
|===


2+| Type d'élément principal 3+| Description 


2+| Protocoles hôtes 3+| NFS, SMB/CIFS, iSCSI et NVMe sur TCP 


2+| Options de déploiement 3+| Nœud unique, cluster à deux nœuds (paire haute disponibilité), cluster à quatre, six, huit, dix ou douze nœuds 


2+| Capacité prise en charge (par nœud) 3+| Jusqu'à 400 To de données brutes (ESXi et KVM) 
|===
--
.Matériel
--
[cols="5"30"]
|===


2+| Type de matériel 3+| Description 


2+| Taille de l'instance | Petit | Moyen | Grand 


2+| Famille de processeurs | Intel Xeon E5-26xx v3 (Haswell) ou version ultérieure | Intel Xeon E5-26xx v3 (Haswell) ou version ultérieure | Intel Xeon E5-26xx v3 (Haswell) ou version ultérieure 


2+| Processeur/mémoire ONTAP Select | 4 processeurs virtuels (vCPUs) / 16 Go de RAM | 8 vCPU / 64 Go de RAM | 16 vCPU / 128 Go de RAM 


2+| Configuration minimale requise pour le processeur et la mémoire de l'hôte ^1^ | 6 cœurs / 24 Go de RAM | 10 cœurs / 72 Go de RAM | 18 cœurs / 136 Go de RAM 


2+| Réseau (par nœud) 3+| Un cluster à un seul nœud nécessite au minimum deux ports 1GbE. Un cluster à deux nœuds (paire haute disponibilité) nécessite au minimum quatre ports 1GbE. Un cluster à quatre, six, huit, dix ou douze nœuds nécessite au minimum deux ports 10GbE. 
|===
^1^ Suppose deux cœurs et 8 Go de RAM pour l'hyperviseur.

--
.Type de stockage
--
Le tableau suivant indique le type de licence minimal requis pour le stockage spécifié. 

[cols="5"30"]
|===


2+| Type de stockage 3+| Description 


2+| Type de licence | Standard | Premium | XL haut de gamme 


2+| Taille de l'instance | Petit | Petites et moyennes | Petit, moyen et grand 


2+| DAS local avec contrôleur RAID matériel | 8 à 60 disques | 8 à 60 disques | 8 à 60 disques 


2+| Disque dur (SAS, NL-SAS, SATA) | Non Concerné | 4 à 60 disques | 4 à 60 disques 


2+| SSD (SAS) | Non Concerné | 4 à 60 disques (SSD uniquement) | 4 à 60 disques (SSD uniquement) 


2+| DAS local avec RAID logiciel | Non Concerné | En vigueur | 4 à 14 disques (NVMe uniquement) 


2+| Baies externes ^1^ 3+| Les banques de données hébergées sur des baies externes sont connectées via FC, FCoE, iSCSI et NFS (NFS n'est pas pris en charge pour KVM). Ces banques de données offrent une haute disponibilité et une grande résilience. 
|===
^1^ La prise en charge du protocole de baie externe reflète la connectivité du stockage en réseau.

--
.Logiciels
--
[cols="5"30"]
|===


2+| Type de logiciel 3+| Description 


2+| Prise en charge de l'hyperviseur (VMware) 3+| VMware vSphere 9.0 VMware vSphere 8.0GA et mises à jour 1 à 3 VMware vSphere 7.0GA et mises à jour 1 à 3C 


2+| Prise en charge de l'hyperviseur (KVM)  a| 
Red Hat Enterprise Linux 64-bit (KVM) 10.1, 10.0, 9.7, 9.6, 9.5, 9.4, 9.3, 9.2, 9.1, 9.0, 8.8, 8.7 et 8.6

Rocky Linux (KVM) 10.1, 10.0, 9.7, 9.6, 9.5, 9.4, 9.3, 9.2, 9.1, 9.0, 8.9, 8.8, 8.7, et 8.6



2+| Logiciel de gestion 3+| NetApp Active IQ Unified Manager management suite ONTAP Select Deploy Utility SnapCenter (facultatif) 
|===
--
====
.Et ensuite ?
link:concept_lic_workflow.html["Découvrez comment acheter une licence ONTAP Select"]
