---
sidebar: sidebar 
permalink: concept_terminology.html 
keywords: terminology, key concepts, concepts 
summary: 'Lorsque vous commencez à explorer ONTAP Select et à planifier un déploiement, il est utile de vous familiariser d"abord avec la terminologie et les concepts clés.' 
---
= Terminologie et concepts clés d'ONTAP Select
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Lorsque vous commencez à explorer ONTAP Select et à planifier un déploiement, il est utile de vous familiariser d'abord avec la terminologie et les concepts clés.

ONTAP Select Deploy:: ONTAP Select Deploy est l'utilitaire d'administration que vous utilisez pour déployer des clusters ONTAP Select. L'utilitaire Deploy s'exécute dans une machine virtuelle Linux dédiée. Vous pouvez accéder à l'utilitaire Deploy via l'interface utilisateur web, le shell de gestion CLI et l'API REST.
Machine virtuelle basée sur le noyau:: La machine virtuelle basée sur le noyau (KVM) est une fonctionnalité de virtualisation du noyau Linux, qui lui permet d'agir en tant que plateforme d'hyperviseur. Elle prend en charge un large éventail de systèmes d'exploitation invités.
Hôte hyperviseur versus nœud ONTAP Select:: Un hôte hyperviseur est la plateforme matérielle principale qui héberge une machine virtuelle ONTAP Select. Lorsqu'une machine virtuelle ONTAP Select est déployée et active sur un hôte hyperviseur, elle est considérée comme un nœud ONTAP Select.
Cluster ONTAP Select:: Vous pouvez créer un cluster ONTAP Select composé d'un, deux, quatre, six, huit, dix ou douze nœuds. Les clusters à plusieurs nœuds contiennent toujours une ou plusieurs paires haute disponibilité. Par exemple, un cluster à quatre nœuds comprend deux paires haute disponibilité. Un cluster à un seul nœud ne fournit pas de capacité de haute disponibilité.
Préparation de l'environnement hôte de l'hyperviseur:: Avant d'utiliser l'utilitaire d'administration Deploy pour déployer un cluster ONTAP Select, vous devez préparer les hôtes hyperviseurs sur lesquels ONTAP Select s'exécutera, y compris les environnements de stockage et de réseau. Cette préconfiguration des hôtes est effectuée en dehors du produit ONTAP Select en fonction des exigences et limitations actuelles.
Déploiements d'évaluation versus déploiements en production:: Chaque nœud ONTAP Select fonctionne soit avec une , soit avec une . Une licence d'évaluation vous permet d'évaluer ONTAP Select avant de le déployer dans un environnement de production. La licence d'évaluation est générée et appliquée automatiquement. Si vous déployez un cluster dans un environnement de production, vous devez acheter une licence, ce qui implique de choisir :
+
--
* Modèle de licence
* Capacité de stockage
* offre de licence de plateforme


--
Modèle de licence à niveaux de capacité:: Le modèle de licence par niveaux de capacité est l'option d'origine pour la gestion du stockage dans un déploiement ONTAP Select. Il est basé sur le modèle ONTAP utilisé avec NetApp AFF et FAS. Une licence distincte est requise pour chaque nœud. La capacité de stockage est liée au nœud et perpétuelle (aucun renouvellement n'est nécessaire).
Modèle de licence des pools de capacité:: Le modèle de licence des pools de capacité a été introduit avec ONTAP Select 9.5 utilisant Deploy 2.10. Une licence distincte est requise pour chaque pool de capacité de stockage. La licence du pool de capacité est liée à une instance de License Manager (c'est-à-dire une instance Deploy) et doit être renouvelée selon les conditions de votre achat. Vous pouvez licencier et utiliser autant de pools de capacité que vous le souhaitez dans votre organisation. Cependant, comme les pools de capacité sont partagés par les nœuds ONTAP Select, moins de licences sont généralement requises que pour le modèle de licence Capacity Tiers.
Gestionnaire de licences:: Le Gestionnaire de licences est un composant logiciel qui prend en charge la gestion des licences des Capacity Pools. Il fait actuellement partie de l'utilitaire d'administration Deploy. LM loue du stockage aux nœuds ONTAP Select à partir des pools partagés qu'il gère. L'_identifiant de verrouillage de licence_ (LLID) est une chaîne numérique qui identifie de manière unique chaque instance LM, et donc chaque instance Deploy. Vous devez utiliser à la fois le numéro de série de la licence Capacity Pool et le LLID pour générer un fichier de licence.
Offres de licences de plateforme:: Trois offres de licence sont disponibles et déterminent les capacités de taille de la machine virtuelle ONTAP Select lors de l'achat d'une licence :
+
--
* Standard
* Premium
* XL haut de gamme


--


Pour plus d'informations, reportez-vous aux deux sections link:concept_workflow_deploy.html["Planifier"] et link:concept_lic_evaluation.html["Licence"].

Pools de stockage versus datastores:: Un _pool de stockage_ ONTAP Select est un container de données logique conçu pour abstraire et masquer le stockage physique sous-jacent. Un pool de stockage est indépendant de l'hyperviseur. Lorsqu'il est déployé sur un hôte hyperviseur ESXi, le pool de stockage ONTAP Select est synonyme du _datastore_ VMware.
MTU de cluster:: La fonctionnalité Cluster MTU permet de configurer la taille MTU utilisée sur le réseau interne avec un cluster multi-nœuds ONTAP Select. L'utilitaire d'administration Deploy ajuste la taille MTU lors de la configuration des paires haute disponibilité afin de s'adapter à votre environnement réseau. Vous pouvez également définir la valeur manuellement.
ONTAP Select vNAS:: La solution ONTAP Select vNAS permet à un nœud ONTAP Select d'accéder aux datastores VMware sur un stockage externe. Avec ONTAP Select vNAS, un contrôleur RAID local n'est plus nécessaire ; la fonctionnalité RAID est supposée être assurée par le stockage distant. ONTAP Select vNAS peut être configuré de la manière suivante :
+
--
* VMware vSAN
* baie de stockage externe générique


--


Dans les deux cas, le stockage externe doit être configuré avant la création d'un cluster ONTAP Select ou l'extension de la capacité de stockage d'un nœud existant.

Réhébergement du nœud sur la machine virtuelle ESXi:: Lorsque vous déployez un cluster utilisant un stockage externe disponible via la solution ONTAP Select vNAS (soit VMware vSAN, soit une baie de stockage externe générique), la machine virtuelle ESXi hébergeant le nœud ONTAP Select peut être déplacée grâce à des actions utilisant les fonctionnalités VMware suivantes :
+
--
* vMotion
* Haute disponibilité (HA)
* Planificateur de ressources distribuées (DRS)
+
L'utilitaire ONTAP Select Deploy détecte le déplacement de la machine virtuelle lors de l'exécution d'une opération sur le cluster, par exemple :

* cluster en ligne
* cluster hors ligne
* ajout de stockage
+
Lorsqu'une machine virtuelle est déplacée, l'utilitaire Deploy met à jour sa base de données interne et configure le nouvel hôte ESXi. Toutes les actions effectuées sur le nœud ONTAP Select sont bloquées jusqu'à la fin du déplacement de la machine virtuelle et des mises à jour de Deploy.



--
Open vSwitch pour KVM:: Open vSwitch (OVS) est une implémentation logicielle d'un commutateur virtuel prenant en charge plusieurs protocoles réseau. OVS est un logiciel libre et distribué sous licence Apache 2.0.
Service de médiation:: L'utilitaire ONTAP Select Deploy inclut un service de médiation qui se connecte aux nœuds des clusters actifs à deux nœuds. Ce service surveille chaque paire haute disponibilité et contribue à la gestion des pannes.



CAUTION: Si vous disposez d'un ou plusieurs clusters à deux nœuds actifs, la machine virtuelle ONTAP Select Deploy qui administre ces clusters doit être en cours d'exécution en permanence. Si la machine virtuelle Deploy est arrêtée, le service de médiation devient indisponible et la capacité de haute disponibilité est perdue pour les clusters à deux nœuds.

MetroCluster SDS:: MetroCluster SDS est une fonctionnalité qui offre une option de configuration supplémentaire lors du déploiement d'un cluster ONTAP Select à deux nœuds. Contrairement à un déploiement ROBO classique à deux nœuds, les nœuds MetroCluster SDS peuvent être séparés par une distance bien plus grande. Cette séparation physique permet des cas d'utilisation supplémentaires, comme la reprise après sinistre. Vous devez disposer d'une licence Premium ou supérieure pour utiliser MetroCluster SDS. De plus, le réseau entre les nœuds doit respecter une exigence minimale de latence.
Magasin d'identifiants:: Le magasin d'identifiants Deploy est une base de données sécurisée contenant les identifiants de compte. Il est principalement utilisé pour enregistrer des hôtes hyperviseur lors de la création d'un nouveau cluster. Consultez la link:concept_workflow_deploy.html["Planifier"] section pour plus d'informations.
efficacité de stockage:: ONTAP Select propose des options d'efficacité du stockage similaires à celles présentes sur les baies FAS et AFF. Conceptuellement, ONTAP Select avec stockage direct (DAS) SSD (avec une licence premium) est similaire à une baie AFF. Les configurations utilisant DAS avec des HDD et toutes les configurations vNAS doivent être considérées comme similaires à une baie FAS. La principale différence entre les deux configurations est qu'ONTAP Select avec DAS SSD prend en charge la déduplication en ligne au niveau de l'agrégat et la déduplication en arrière-plan au niveau de l'agrégat. Les autres options d'efficacité du stockage sont disponibles pour les deux configurations.
+
--
Les configurations par défaut de vNAS activent une fonction d'optimisation en écriture appelée journalisation des données à instance unique (SIDL). Avec ONTAP Select 9.6 et les versions ultérieures, les fonctionnalités d'efficacité du stockage ONTAP en arrière-plan sont qualifiées lorsque SIDL est activé. Consultez la link:concept_stor_concepts_chars.html["Analyse approfondie"] section pour plus d'informations.

--
Actualisation du cluster:: Après la création d'un cluster, vous pouvez modifier la configuration du cluster ou de la machine virtuelle en dehors de l'utilitaire Deploy à l'aide des outils d'administration ONTAP ou de l'hyperviseur. Vous pouvez également migrer une machine virtuelle, ce qui entraîne des modifications de configuration. Lorsque ces modifications se produisent, l'utilitaire Deploy n'est pas mis à jour automatiquement et peut se désynchroniser avec l'état du cluster. Vous pouvez utiliser la fonctionnalité d'actualisation du cluster pour mettre à jour la base de données de configuration de Deploy. L'actualisation du cluster est disponible via l'interface web de Deploy, le shell de gestion CLI et l'API REST.
RAID logiciel:: Lors de l'utilisation d'un stockage à connexion directe (DAS), la fonctionnalité RAID est généralement assurée par un contrôleur RAID matériel local. Vous pouvez également configurer un nœud pour utiliser le , où le nœud ONTAP Select fournit la fonctionnalité RAID. Si vous utilisez le RAID logiciel, un contrôleur RAID matériel n'est plus nécessaire.


[[ontap-select-image-install]]
Installation de l'image ONTAP Select:: L'utilitaire d'administration Deploy ne contient qu'une seule version de ONTAP Select. La version incluse est la plus récente disponible au moment de la publication. La fonctionnalité d'installation d'images ONTAP Select vous permet d'ajouter des versions antérieures de ONTAP Select à votre instance de l'utilitaire Deploy, qui pourront ensuite être utilisées lors du déploiement d'un cluster ONTAP Select. Voir link:task_cli_deploy_image_add.html["Ajouter des images ONTAP Select pour plus d'informations"].



NOTE: Vous ne devez ajouter une image ONTAP Select que si sa version est antérieure à celle fournie avec votre instance de Deploy. L'ajout de versions ultérieures d'ONTAP Select sans mise à jour simultanée de Deploy n'est pas pris en charge.

Administration d'un cluster ONTAP Select après son déploiement:: Après avoir déployé un cluster ONTAP Select, vous pouvez configurer le cluster comme vous le feriez avec un cluster ONTAP basé sur du matériel. Par exemple, vous pouvez configurer un cluster ONTAP Select à l'aide de System Manager ou de l'interface de ligne de commandes ONTAP standard.


.Informations connexes
link:task_cli_deploy_image_add.html["Ajouter une image ONTAP Select à Deploy"]
