---
sidebar: sidebar 
permalink: concept_lic_cp_operation.html 
keywords: license, licensing, Capacity Pools, operation details 
summary: 'Le modèle de licence Capacity Pools diffère du modèle Capacity Tiers. Au lieu d"allouer une capacité de stockage à chaque nœud, celle-ci est répartie dans un pool et partagée entre plusieurs nœuds. Des composants et processus supplémentaires ont été développés pour prendre en charge le modèle Capacity Pools.' 
---
= Détails opérationnels du modèle de licence ONTAP Select Capacity Pools
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Le modèle de licence Capacity Pools diffère du modèle Capacity Tiers. Au lieu d'allouer une capacité de stockage à chaque nœud, celle-ci est répartie dans un pool et partagée entre plusieurs nœuds. Des composants et processus supplémentaires ont été développés pour prendre en charge le modèle Capacity Pools.



== Gestionnaire de licences

Le gestionnaire de licences s'exécute en tant que processus distinct au sein de chaque instance de l'utilitaire d'administration Deploy. Certaines des fonctions fournies par LM incluent :

* Générez un numéro de série unique à vingt chiffres pour chaque nœud basé sur le numéro de série de la licence Capacity Pool
* Créer des baux de capacité à partir des pools de capacité partagés en fonction des demandes provenant des nœuds ONTAP Select
* Signalez les informations d'utilisation du pool via l'interface utilisateur Deploy




== Caractéristiques du bail

L'espace de stockage alloué à chaque agrégat de données sur un nœud utilisant une licence de pool de capacité doit être associé à un bail. Le nœud demande un bail de stockage et, si la capacité est disponible, le License Manager répond par un bail. Chaque bail possède les attributs explicites ou implicites suivants :

* Gestionnaire de licences
+
Chaque nœud ONTAP Select est associé à une instance de License Manager

* Pool de capacité
+
Chaque nœud ONTAP Select est associé à un pool de capacité

* Allocation de stockage
+
Une valeur de capacité spécifique est attribuée dans le bail

* Date et heure d'expiration
+
Les baux ont une durée comprise entre une heure et sept jours selon la configuration de l'utilisateur.





== ID de verrouillage de licence

Chaque instance du Gestionnaire de licences, et par conséquent chaque instance correspondante de l'utilitaire Deploy, est identifiée par un numéro unique de 128 bits. Ce numéro est combiné avec le numéro de série de licence du pool de capacité à neuf chiffres pour verrouiller le pool à une instance spécifique du Gestionnaire de licences (qui correspond en réalité à une instance Deploy). Vous devez fournir ces deux valeurs sur le site d'assistance NetApp lors de la génération du fichier de licence NetApp (NLF).

Vous pouvez déterminer l'ID de verrouillage de licence de votre instance Deploy à l'aide de l'interface utilisateur Web de la manière suivante :

* Page de démarrage
+
Deploy affiche cette page lors de votre première connexion. Vous pouvez également ouvrir le menu déroulant en haut à droite de la page et sélectionner *Getting Started* pour afficher cette page. Le LLID s'affiche dans la section Ajouter des licences.

* Sélectionnez l’onglet *Administration* en haut de la page, puis sélectionnez *Systèmes & AutoSupport*.




== Opérations de location de base

Un nœud ONTAP Select doit localiser ou demander un bail de capacité valide chaque fois qu'un agrégat de données est créé, étendu ou modifié. Vous pouvez utiliser un bail obtenu lors d'une demande précédente qui est toujours valide, ou vous pouvez demander un nouveau bail si nécessaire. Les étapes suivantes sont effectuées par le nœud ONTAP Select pour localiser un bail de Capacity Pool :

. Si un bail existant est situé au niveau du nœud, il est utilisé tant que toutes les conditions suivantes sont remplies :
+
** Le bail n'a pas expiré
** La demande de stockage pour l'agrégat ne dépasse pas la capacité de location.


. Si aucun bail existant ne peut être localisé, le nœud demande un nouveau bail au License Manager.




== Restituer la capacité de stockage à un pool de capacité

La capacité de stockage est allouée à partir d'un pool de capacité en fonction des besoins, et chaque nouvelle demande peut réduire la capacité disponible dans le pool. La capacité de stockage est restituée au pool dans plusieurs situations, notamment :

* Le bail d'un agrégat de données expire et n'est pas renouvelé par le nœud
* L’agrégat de données est supprimé



NOTE: Si une machine virtuelle ONTAP Select est supprimée, les baux actifs restent valides jusqu'à leur expiration. Lorsque cela se produit, la capacité est remise dans le pool.
