---
sidebar: sidebar 
permalink: concept_ots_deploy.html 
keywords: ontap select deploy, deploy administration utility, deploy utility, functionality, accessing 
summary: 'ONTAP Select Deploy est l"utilitaire d"administration utilisé pour déployer et gérer les clusters ONTAP Select.' 
---
= ONTAP Select Deploy
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
ONTAP Select Deploy est l'utilitaire d'administration utilisé pour déployer et gérer les clusters ONTAP Select. Deploy est fourni sous forme de machine virtuelle Linux que vous devez installer avant de créer un cluster ONTAP Select.



== fonctionnalité principale

L'utilitaire d'administration Deploy remplit les fonctions principales suivantes :

* Consignez les détails de chaque hôte hyperviseur sur lequel ONTAP Select est déployé
* Configurez les hôtes et installez les licences requises
* Déployer et gérer les clusters ONTAP Select
* Tenir à jour un inventaire des clusters ONTAP Select et des hôtes
* Collecter et envoyer des données AutoSupport à NetApp
* Conserver un ensemble interne d’images de nœud ONTAP Select
* Prise en charge des formats de commandes et des protocoles spécifiques à l'hyperviseur




== Façons d'accéder à l'utilitaire de déploiement

Plusieurs options s'offrent à vous pour accéder à l'utilitaire d'administration Deploy. Toutes les interfaces externes sont fonctionnellement équivalentes. Vous devez choisir l'option d'accès qui correspond le mieux à vos objectifs et exigences de déploiement spécifiques. Dans tous les cas, vous devez vous connecter avec le compte administrateur et un mot de passe valide.



=== interface utilisateur graphique Web

Vous pouvez accéder à l'utilitaire Deploy via un navigateur web moderne. L'interface utilisateur web offre une interface intuitive et facile à utiliser, et dans la plupart des cas, elle sera votre interface principale lors de l'utilisation de l'utilitaire.



=== interface de ligne de commandes

Une interface de ligne de commandes en mode texte est disponible via l'interpréteur de commandes. Vous pouvez accéder à l'interpréteur de commandes de gestion de la ligne de commandes de la manière suivante :

* Secure shell (SSH)
* console de machine virtuelle


On utilise généralement la console de la machine virtuelle lors de l'installation et de la configuration initiale. Cependant, dans la plupart des cas, SSH offre une option plus flexible et plus pratique.



=== API de services web REST

L'API de services web REST exposée aux clients externes offre une autre option de connexion à l'utilitaire Deploy. Vous pouvez accéder à l'API à l'aide de n'importe quel langage de programmation ou outil courant prenant en charge les services web REST. Les choix populaires incluent :

* Python
* Java
* Curl


L'utilisation d'un langage de programmation ou de script offre la possibilité d'automatiser le déploiement et la gestion des clusters ONTAP Select.



=== Page Web de documentation en ligne ONTAP Select

L'affichage de la page Web de documentation en ligne dans l'utilitaire de déploiement constitue une autre méthode d'accès à l'API des services Web REST. Toutefois, au lieu d'utiliser un langage de programmation, vous accédez à l'API de gestion via la page à l'aide d'un navigateur. Les fonctionnalités suivantes sont disponibles :

* Une description détaillée de chaque appel dans l'API des services Web REST
* La possibilité d'émettre manuellement n'importe quel appel d'API


Vous pouvez accéder à la page de documentation en ligne à l'aide de l'adresse IP ou du nom de domaine de la machine virtuelle Deploy. Pour afficher la page, saisissez une URL au format suivant dans votre navigateur (en remplaçant l'adresse IP ou le nom de domaine par celui de votre instance Deploy VM) : `\http://<ip_address>/api/ui`
