---
sidebar: sidebar 
permalink: reference_plan_ots_kvm.html 
keywords: plan, planning, vnas, kvm 
summary: 'Plusieurs points relatifs à la planification de l"utilisation de l"hyperviseur KVM doivent être pris en compte.' 
---
= Exigences de stockage externe KVM pour ONTAP Select
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Vous pouvez configurer ONTAP Select sur l'hyperviseur KVM avec une baie de stockage externe.



== Exigences et restrictions de base

Si vous utilisez une baie externe pour les pools de stockage ONTAP Select, les restrictions de configuration suivantes s'appliquent :

* Vous devez définir comme type de pool logique en utilisant CLVM.
* Vous devez indiquer une limite de capacité de stockage.
* Cette configuration prend uniquement en charge les protocoles FC, Fibre Channel over Ethernet (FCoE) et iSCSI.
* La configuration ne reconnaît pas le stockage à provisionnement fin.



CAUTION: La capacité de stockage que vous spécifiez doit respecter les limites de stockage autorisées du stockage externe. Une erreur se produit si vous ne spécifiez pas de limite de capacité ou si le stockage externe est saturé pendant la création du disque.



== Meilleures pratiques

Vous devriez suivre ces bonnes pratiques :

* Définissez les ports réseau dédiés, la bande passante et les configurations vSwitch pour les réseaux ONTAP Select et le stockage externe
* Configurez l'option de capacité pour limiter l'utilisation du stockage (ONTAP Select ne peut pas consommer la totalité de la capacité d'un pool de stockage externe)
* Vérifiez que toutes les baies de stockage externes utilisent les fonctionnalités de redondance et de haute disponibilité (HA) disponibles dans la mesure du possible

