---
sidebar: sidebar 
permalink: reference_plan_dep_vmware.html 
keywords: plan, planning, ontap select deploy, vmware requirements 
summary: 'Il existe plusieurs exigences et restrictions spécifiques à l"environnement VMware que vous devez prendre en compte avant d"installer l"utilitaire ONTAP Select Deploy dans un environnement VMware.' 
---
= Considérations relatives à l'hôte de l'hyperviseur ONTAP Select Deploy
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Il existe plusieurs points de planification relatifs à l'hôte de l'hyperviseur que vous devriez prendre en compte.


CAUTION: Vous ne devez pas modifier directement la configuration d'une machine virtuelle ONTAP Select, sauf indication contraire du support NetApp. Une machine virtuelle ne doit être configurée et modifiée que via l'utilitaire d'administration Deploy. Apporter des modifications à une machine virtuelle ONTAP Select en dehors de l'utilitaire Deploy, sans l'assistance du support NetApp, peut entraîner une défaillance de la machine virtuelle et la rendre inutilisable.



== Hyperviseur indépendant

ONTAP Select et l'utilitaire d'administration ONTAP Select Deploy sont tous deux indépendants de l'hyperviseur.

Les hyperviseurs suivants sont pris en charge à la fois pour ONTAP Select et pour l'administration d'ONTAP Select Deploy :

* VMware ESXi
* Machine virtuelle basée sur le noyau (KVM)



NOTE: Veuillez vous référer aux informations de planification spécifiques à l'hyperviseur et link:reference_release_notes.html["notes de version"] pour des détails supplémentaires concernant les plateformes prises en charge.

.Hyperviseur pour les nœuds ONTAP Select et utilitaire d'administration
L'utilitaire d'administration Deploy et les nœuds ONTAP Select s'exécutent tous deux en tant que machines virtuelles. L'hyperviseur que vous choisissez pour l'utilitaire Deploy est indépendant de l'hyperviseur que vous choisissez pour les nœuds ONTAP Select. Vous disposez d'une flexibilité totale quant à l'association des deux :

* L'utilitaire de déploiement exécuté sur VMware ESXi peut créer et gérer des clusters ONTAP Select sur VMware ESXi ou KVM
* L'utilitaire de déploiement exécuté sur KVM peut créer et gérer des clusters ONTAP Select sur VMware ESXi ou KVM


.Une ou plusieurs instances de nœud ONTAP Select par hôte
Chaque nœud ONTAP Select s'exécute comme une machine virtuelle dédiée. Vous pouvez créer plusieurs nœuds sur le même hôte hyperviseur, sous réserve des restrictions suivantes :

* Plusieurs nœuds d'un même cluster ONTAP Select ne peuvent pas s'exécuter sur le même hôte. Tous les nœuds d'un hôte donné doivent appartenir à des clusters ONTAP Select différents.
* Vous devez utiliser un stockage externe.
* Si vous utilisez un RAID logiciel, vous ne pouvez déployer qu'un seul nœud ONTAP Select sur l'hôte.


.Cohérence de l'hyperviseur pour les nœuds au sein d'un cluster
Tous les hôtes d'un cluster ONTAP Select doivent exécuter la même version et la même mise à jour du logiciel hyperviseur.

.Nombre de ports physiques sur chaque hôte
Vous devez configurer chaque hôte pour utiliser un, deux ou quatre ports physiques. Bien que vous ayez une certaine flexibilité lors de la configuration des ports réseau, il est conseillé de suivre ces recommandations dans la mesure du possible :

* Un hôte dans un cluster à nœud unique doit disposer de deux ports physiques.
* Chaque hôte d'un cluster multi-nœuds doit avoir quatre ports physiques


.Intégrez ONTAP Select à un cluster ONTAP basé sur du matériel
Vous ne pouvez pas ajouter un nœud ONTAP Select directement à un cluster ONTAP basé sur du matériel. Cependant, vous pouvez éventuellement établir une relation de peering de cluster entre un cluster ONTAP Select et un cluster ONTAP basé sur du matériel.



== Environnement d'hyperviseur VMware

Il existe plusieurs exigences et restrictions spécifiques à l'environnement VMware que vous devez prendre en compte avant d'installer l'utilitaire ONTAP Select Deploy dans un environnement VMware.

.Configuration matérielle requise pour le serveur hôte ESXi
Il existe plusieurs exigences minimales en matière de ressources que votre hôte hyperviseur ESXi doit respecter. Assurez-vous que les hôtes sur lesquels ONTAP Select est déployé répondent aux exigences de base suivantes :

* Serveur ESXi :
+
** Le matériel et les logiciels doivent être 64 bits
** Doit respecter les mêmes versions prises en charge que celles définies pour un nœud ONTAP Select


* Processeurs virtuels (2)
* mémoire virtuelle (4 Go)
* Stockage (40 Go)
* DHCP activé (peut également attribuer une adresse IP statique)


.connectivité réseau
Vous devez vous assurer que l'interface réseau de la machine virtuelle ONTAP Select Deploy est configurée et possède une seule adresse IP de gestion. Vous pouvez utiliser DHCP pour attribuer dynamiquement une adresse IP ou configurer manuellement une adresse IP statique.

Selon vos choix de déploiement, la machine virtuelle de déploiement doit pouvoir se connecter au serveur vCenter, aux hôtes hyperviseur ESXi et aux nœuds ONTAP Select qu'elle gère. Vous devez configurer vos pare-feu pour autoriser le trafic requis.

Deploy utilise l'API VMware VIX pour communiquer avec le vCenter server et les hôtes ESXi. Dans un premier temps, une connexion est établie via SOAP sur SSL sur le port TCP 443. Ensuite, une connexion est ouverte via SSL sur le port 902. De plus, Deploy effectue des requêtes PING pour vérifier la présence d'un hôte ESXi à l'adresse IP spécifiée.

Deploy doit également pouvoir communiquer avec les adresses IP de gestion du nœud et du cluster ONTAP Select en utilisant les protocoles suivants :

* Commande PING (ICMP)
* SSH (port 22)
* SSL (port 443)


.Prise en charge de la version 4 du protocole IP
ONTAP Select Deploy prend uniquement en charge la version IP 4 (IPv4). La version IP 6 (IPv6) n'est pas prise en charge. Cette restriction affecte ONTAP Select de la manière suivante :

* Vous devez attribuer une adresse IPv4 à l'interface LIF de gestion de la machine virtuelle Deploy.
* Le déploiement ne peut pas créer des nœuds ONTAP Select configurés pour utiliser IPv6 sur les LIF ONTAP.




== Considérations relatives au serveur VMware vCenter pour le déploiement d'ONTAP Select



=== Privilèges VMware vSphere pour ESA

La liste suivante répertorie les privilèges spécifiques pour la bibliothèque de contenu vSphere dont vous avez besoin pour créer et gérer vSAN Express Storage Architecture (ESA) dans vCenter :

* Ajouter un élément de bibliothèque
* Créer une bibliothèque locale
* Supprimer l'élément de bibliothèque
* Supprimer la bibliothèque locale
* Télécharger les fichiers
* Stockage de lecture
* Mettre à jour les fichiers
* Mise à jour de la bibliothèque
* Mettre à jour l'élément de bibliothèque
* Mettre à jour la bibliothèque locale
* Afficher les paramètres de configuration

