---
sidebar: sidebar 
permalink: reference_faq.html 
keywords: faq, frequently asked questions 
summary: Trouvez les réponses aux questions fréquentes concernant ONTAP Select. 
---
= FAQ pour ONTAP Select
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Vous trouverez ici les réponses aux questions fréquemment posées sur ONTAP Select.

[NOTE]
====
À compter d'ONTAP Select 9.14.1, la prise en charge de l'hyperviseur KVM a été rétablie. Auparavant, la prise en charge du déploiement d'un nouveau cluster sur un hyperviseur KVM avait été supprimée dans ONTAP Select 9.10.1 et la prise en charge de la gestion des clusters et hôtes KVM existants, à l'exception de la mise hors ligne ou de la suppression, avait été supprimée dans ONTAP Select 9.11.1.

====


== Général

Il existe plusieurs questions et réponses générales.

.Quelle est la différence entre ONTAP Select Deploy et ONTAP Select?
ONTAP Select Deploy est l'utilitaire utilisé pour créer des clusters ONTAP Select. Actuellement, ONTAP Select Deploy est la seule méthode disponible pour créer un cluster de production. ONTAP Select Deploy peut également être utilisé pour créer un cluster Select d'évaluation afin de permettre aux clients de tester et de documenter les étapes réelles d'un déploiement en production. ONTAP Select Deploy peut également convertir un cluster d'évaluation en cluster de production à l'aide d'une licence Capacity Tier appropriée, offrant une capacité suffisante pour couvrir l'espace consommé lors de l'évaluation.

ONTAP Select Deploy est une machine virtuelle qui contient une image d'ONTAP Select. Lors de l'installation du cluster, ONTAP Select Deploy effectue plusieurs vérifications afin de garantir que les exigences minimales d'ONTAP Select sont respectées. La machine virtuelle ONTAP Select Deploy et les clusters Select peuvent être mis à niveau séparément.

.Comment puis-je résoudre un problème de performance avec ONTAP Select?
Tout comme pour ONTAP sur FAS, les données de performance doivent être collectées à l'aide de l'utilitaire perfstat. Voici un exemple de commande :

[listing]
----
perfstat8 –i N,m -t <sample time in minutes> --verbose --nodes=<filer IP> --diag-passwd=abcxyz --mode="cluster-mode" > <name of output file>
----
.Comment accéder à la page de l'API Swagger pour ONTAP Select Deploy ?
[listing]
----
http://<Deploy-IP-Address/api/ui
----

NOTE: La version 3 de l'API n'est pas compatible avec la version précédente de l'API. Une nouvelle procédure API est disponible sur le https://library.netapp.com/ecm/ecm_download_file/ECMLP2845694["Field Portal"^].

.La machine virtuelle ONTAP Select peut-elle être sauvegardée avec des instantanés VMware ou d'autres solutions tierces ?
Non. La machine virtuelle ONTAP Select utilise des disques indépendants-persistants, qui sont exclus des snapshots VMware. La seule méthode prise en charge pour la sauvegarde ONTAP Select est SnapMirror ou SnapVault.

.Où puis-je obtenir des clarifications pour les questions qui ne sont pas couvertes dans cette FAQ ?
Contactez link:mailto:ng-ses-ontap-select@netapp.com["ng-ses-ontap-select@netapp.com"].



== Licences, installation, mises à jour et restaurations

Vous trouverez plusieurs questions et réponses concernant les licences, l'installation, les mises à jour et les restaurations.

.ONTAP Select et ONTAP Select Deploy peuvent-ils être mis à niveau séparément ?
Oui. L'utilitaire ONTAP Select Deploy peut être mis à niveau indépendamment du cluster ONTAP Select. De même, le cluster Select peut être mis à niveau indépendamment de l'utilitaire ONTAP Select Deploy.

.ONTAP Select peut-il être mis à niveau en utilisant la même procédure qu'un cluster FAS ?
Oui, la procédure de mise à niveau d'un cluster Select est identique à celle d'un cluster FAS, bien que le fichier binaire de mise à niveau ONTAP Select soit un téléchargement distinct du fichier binaire de mise à niveau ONTAP sur FAS.

.ONTAP Select peut-il être restauré en utilisant la même procédure qu'un cluster FAS ?
Oui, la procédure de restauration d'un cluster ONTAP Select est presque identique à celle d'un cluster FAS. Il existe cependant quelques différences :

* Seules les instances mises à niveau d'ONTAP Select peuvent être restaurées, et uniquement jusqu'à la version d'installation d'origine. Les nouvelles installations ne peuvent pas être restaurées à une version antérieure, même si ONTAP Select prend généralement en charge cette version.
* Pour ONTAP Select (KVM) et ONTAP Select (ESXi) utilisant le RAID logiciel, il est impossible de revenir à une version antérieure ne prenant pas en charge le RAID logiciel. De plus, une nouvelle installation de ONTAP Select 9.5 ou ultérieure sur ESXi utilise les pilotes réseau VMXNET3 et, lorsque cela est possible, le pilote vNVMe. Ces nouvelles installations ne peuvent pas être restaurées à des versions antérieures de ONTAP Select.
* Si la machine virtuelle ONTAP Select a également été mise à niveau vers une instance Large (à l'aide de la licence Premium XL), le retour à une version antérieure à 9.6 n'est pas pris en charge, car la fonctionnalité d'instance Large n'est pas disponible dans les versions antérieures.


.Le ONTAP MetroCluster SDS requiert-il au minimum une licence Premium ?
Oui.

.Est-il possible de modifier la configuration réseau du cluster ONTAP Select après l'installation ?
Les modifications apportées aux propriétés de cluster ONTAP Select suivantes sont reconnues par ONTAP Select Deploy à l'aide de l'opération d'actualisation du cluster disponible via l'interface utilisateur, la CLI ou l'API REST :

* Configuration réseau (adresses IP, DNS, NTP, masque de sous-réseau et passerelle)
* Cluster ONTAP Select, nom du nœud et version


Les modifications suivantes apportées aux machines virtuelles ONTAP Select sont également prises en compte :

* Nom et état de la machine virtuelle ONTAP Select (par exemple, en ligne ou hors ligne)
* Modifications du nom du réseau hôte et du nom du pool de stockage


La mise à niveau vers ONTAP Select Deploy 2.6 permet la prise en charge de ces modifications pour tout cluster ONTAP Select déjà déployé mais dont la configuration d'origine n'a pas été modifiée. Autrement dit, si les propriétés du cluster ONTAP Select mentionnées ci-dessus ont été modifiées à l'aide de System Manager ou vCenter, alors la mise à niveau vers ONTAP Select Deploy 2.6 ne corrigera pas ces incohérences. Les modifications apportées aux propriétés ONTAP Select doivent d'abord être annulées pour que ONTAP Select Deploy puisse ajouter ses métadonnées uniques à chaque machine virtuelle ONTAP Select.

.Est-il possible de modifier la configuration réseau d'ONTAP Select Deploy après l'installation ?
Il n'est pas possible de modifier les paramètres réseau de l'instance Deploy après son exécution dans un environnement. Pour plus d'informations, consultez l'article de la Knowledge Base link:https://kb.netapp.com/onprem/ontap/ONTAP_Select/Modifying_DNS_configuration_of_ONTAP_Deploy_instance["Modification de la configuration DNS de l'instance ONTAP Deploy"^].

.Comment Deploy détecte-t-il que les licences ONTAP Select sont renouvelées ?
La méthode est la même pour toutes les licences, bien que les détails varient selon qu'il s'agisse d'une licence de niveau de capacité ou d'une licence de pool de capacité.

* ONTAP Select Deploy détecte si les licences et les contrats de support sont renouvelés avec l'achat d'un fichier de licence mis à jour auprès de NetApp. Le fichier de licence (.NLF) inclut la capacité, les dates de début et de fin ; il est généré sur le link:https://mysupport.netapp.com/site/["Site de support NetApp"^], puis mis à jour sur le serveur Deploy.
+

NOTE: Vous pouvez charger le NLF sur le serveur Deploy à l'aide des fonctions *Add* et *Update*. *Add* ajoute de nouvelles licences au serveur, et *Update* met à jour les fichiers existants avec des informations telles que la capacité, la licence de nœud (standard, premium, premium XL), les dates de début et de fin du support (licence Capacity Tier), ou les dates de début et de fin de l'abonnement (licence Capacity Pool).

+

CAUTION: N’essayez pas de modifier le fichier de licence. Toute modification invalidera la clé de sécurité et rendra la licence invalide.

* Une licence *Capacity Tier* est une licence permanente par nœud, liée au numéro de série du nœud ONTAP Select. Elle est vendue avec un contrat de support distinct. Bien que la licence soit permanente, le contrat de support doit être renouvelé pour accéder aux mises à niveau d'ONTAP Select et pour recevoir l'assistance technique de NetApp. Un contrat de support en cours de validité est également requis pour modifier les paramètres de la licence, tels que la capacité ou la taille du nœud.
+
Pour toute mise à jour de licence Capacity Tier, modification de paramètres ou renouvellement de contrat de support, le numéro de série du nœud est requis dans la commande. Les numéros de série des nœuds Capacity Tier comportent neuf chiffres et commencent par le chiffre « 32 ».

+
Une fois l'achat terminé et le fichier de licence généré, celui-ci est téléchargé sur le serveur de déploiement à l'aide de la fonction *Update*.

* Une licence de pool de capacité est un abonnement donnant droit à l'utilisation d'un pool spécifique de capacité et de taille de nœuds (standard, premium, premium XL) pour déployer un ou plusieurs clusters. Cet abonnement inclut le droit d'utiliser une licence et un support technique pendant une période déterminée. Le droit d'utiliser la licence et le contrat de support ont des dates de début et de fin spécifiques.


.Comment Deploy détecte-t-il si les nœuds ont des licences ou un contrat de support renouvelés ?
L'achat, la génération et le téléchargement d'un fichier de licence mis à jour permettent à Deploy de détecter les licences renouvelées et les contrats de support.

Si la date d'expiration d'un contrat de support de niveau de capacité est dépassée, le nœud peut continuer à fonctionner, mais vous ne pourrez pas télécharger et installer les mises à jour ONTAP, ni appeler NetApp support technique pour obtenir de l'aide sans avoir préalablement mis à jour le contrat de support.

Si un abonnement au pool de capacité expire, le système vous avertit d'abord, mais après 30 jours, si le système s'arrête, il ne redémarrera pas tant qu'un abonnement mis à jour n'aura pas été installé sur le serveur de déploiement.



== Stockage

Il existe plusieurs questions et réponses concernant le stockage.

.Une seule instance ONTAP Select Deploy peut-elle créer des clusters à la fois sur ESXi et KVM ?
Oui. ONTAP Select Deploy peut être installé sur KVM ou ESXi, et les deux installations peuvent créer des clusters ONTAP Select sur l'un ou l'autre hyperviseur.

.Est-ce que vCenter est requis pour ONTAP Select sur ESXi ?
Si les hôtes ESXi disposent des licences appropriées, il n'est pas nécessaire qu'ils soient gérés par un vCenter Server. En revanche, s'ils sont gérés par un vCenter Server, vous devez configurer ONTAP Select Deploy pour utiliser ce vCenter Server. Autrement dit, vous ne pouvez pas configurer des hôtes ESXi comme autonomes dans ONTAP Select Deploy s'ils sont activement gérés par un vCenter Server. Notez que la machine virtuelle ONTAP Select Deploy s'appuie sur vCenter pour suivre toutes les migrations de machines virtuelles ONTAP Select entre les hôtes ESXi, suite à un événement vMotion ou de haute disponibilité VMware.

.Qu'est-ce que le RAID logiciel ?
ONTAP Select peut utiliser des serveurs sans contrôleur RAID matériel. Dans ce cas, la fonctionnalité RAID est implémentée par logiciel. Lorsque vous utilisez le RAID logiciel, les disques SSD et NVMe sont pris en charge. Les disques de démarrage et de core d'ONTAP Select doivent toujours résider dans une partition virtualisée (pool de stockage ou datastore). ONTAP Select utilise RD2 (partitionnement root-data-data) pour partitionner les SSD. Par conséquent, la partition racine d'ONTAP Select réside sur les mêmes disques physiques que ceux utilisés pour les agrégats de données. Cependant, l'agrégat racine et les disques virtualisés de démarrage et de core ne sont pas pris en compte dans la licence de capacité.

Toutes les méthodes RAID disponibles sur AFF/FAS sont également disponibles sur ONTAP Select. Cela inclut RAID 4, RAID DP et RAID-TEC. Le nombre minimal de disques SSD varie selon le type de configuration RAID choisie. Les bonnes pratiques exigent la présence d'au moins un disque de secours. Les disques de secours et de parité ne sont pas pris en compte dans la licence de capacité.

.En quoi le RAID logiciel diffère-t-il d'une configuration RAID matérielle ?
Le RAID logiciel est une couche dans la pile logicielle ONTAP. Le RAID logiciel offre un contrôle administratif accru car les disques physiques sont partitionnés et disponibles comme disques bruts au sein de la machine virtuelle ONTAP Select. En revanche, avec le RAID matériel, un seul LUN de grande taille est généralement disponible, qui peut ensuite être divisé pour créer des VMDISKs visibles dans ONTAP Select. Le RAID logiciel est disponible en option et peut être utilisé à la place du RAID matériel.

Voici quelques exigences relatives au RAID logiciel :

* Pris en charge pour ESXi et KVM
+
** À compter d'ONTAP Select 9.14.1, la prise en charge de l'hyperviseur KVM a été rétablie. Auparavant, la prise en charge de l'hyperviseur KVM avait été supprimée dans ONTAP Select 9.10.1.


* Capacité des disques physiques pris en charge : 200 Go à 32 To
* Prise en charge uniquement sur les configurations DAS
* Compatible avec les SSD ou les périphériques NVMe
* Nécessite une licence ONTAP Select Premium ou Premium XL
* Le contrôleur RAID matériel doit être absent ou désactivé ou fonctionner en mode SAS HBA
* Un pool de stockage LVM ou un datastore basé sur un LUN dédié doit être utilisé pour les disques système : core dump, boot/NVRAM et le Mediator.


.Est-ce que ONTAP Select pour KVM prend en charge l’agrégation de plusieurs cartes réseau ?
Lors de l'installation sur KVM, vous devez utiliser une seule agrégation de liens (bond) et un seul pont (bridge). Un hôte doté de deux ou quatre ports physiques doit avoir tous les ports dans la même agrégation de liens (bond).

.Comment ONTAP Select signale-t-il ou alerte-t-il en cas de défaillance d'un disque physique ou d'une carte réseau sur l'hôte de l'hyperviseur ? ONTAP Select récupère-t-il ces informations auprès de l'hyperviseur ou la surveillance doit-elle être configurée au niveau de l'hyperviseur ?
Lorsqu'un contrôleur RAID matériel est utilisé, ONTAP Select ignore généralement les problèmes sous-jacents du serveur. Si le serveur est configuré conformément à nos bonnes pratiques, une certaine redondance devrait exister. Nous recommandons le RAID 5/6 pour survivre à des défaillances de disques. Pour les configurations RAID logicielles, ONTAP est responsable de l’émission d’alertes en cas de défaillance de disques et, s’il existe un disque de secours, d’initier la reconstruction du disque.

Il est recommandé d'utiliser au minimum deux cartes réseau physiques afin d'éviter un point de défaillance unique au niveau de la couche réseau. NetApp recommande de configurer l’agrégation de liens (teaming et bonding) pour les groupes de ports Data, Mgmt et Internal, avec au moins deux liaisons montantes dans l’équipe ou le bond. Cette configuration garantit qu’en cas de défaillance d’une liaison montante, le commutateur virtuel transfère le trafic de la liaison défaillante vers une liaison fonctionnelle au sein de l’équipe de cartes réseau. Pour plus de détails sur la configuration réseau recommandée, consultez link:reference_plan_best_practices.html#networking["Résumé des meilleures pratiques : Réseautage"].

Toutes les autres erreurs sont gérées par ONTAP HA dans le cas d'un cluster à deux ou quatre nœuds. Si le serveur hyperviseur doit être remplacé et que le cluster ONTAP Select doit être reconstitué avec un nouveau serveur, consultez la section _Can I recover an ONTAP Select node?_.

.Puis-je récupérer un nœud ONTAP Select ?
Contactez le support technique NetApp si vous devez récupérer un nœud ONTAP Select, par exemple si une machine virtuelle ONTAP Select ou un hôte est complètement perdu ou si un cluster à nœud unique est supprimé accidentellement. Pour plus d'informations, consultez l'article de la Knowledge Base link:https://kb.netapp.com/on-prem/ontap/ontap-select/Select-KBs/ONTAP_Select_node_VM_recovery_in_case_of_disaster["Récupération de la machine virtuelle du nœud ONTAP Select en cas de sinistre"^].

.Quelle est la taille maximale du datastore prise en charge par ONTAP Select ?
Toutes les configurations, y compris vSAN, prennent en charge 400 To de stockage par nœud ONTAP Select.

Lors de l'installation sur des banques de données plus grandes que la taille maximale prise en charge, vous devez utiliser l'option « Capacity Cap » lors de la configuration du produit.

.Comment puis-je augmenter la capacité d'un nœud ONTAP Select ?
ONTAP Select Deploy intègre un flux de travail d'ajout de stockage permettant d'étendre la capacité d'un nœud ONTAP Select. Vous pouvez étendre le stockage géré en utilisant l'espace disponible sur la même banque de données (si de l'espace est encore disponible) ou en ajoutant de l'espace depuis une banque de données distincte. Le mélange de banques de données locales et distantes au sein d'un même agrégat n'est pas pris en charge.

L'ajout de stockage prend également en charge le RAID logiciel. Toutefois, dans le cas du RAID logiciel, des disques physiques supplémentaires doivent être ajoutés à la machine virtuelle ONTAP Select. L'ajout de stockage dans ce cas est similaire à la gestion d'une baie FAS ou AFF. Les tailles des groupes RAID et des disques doivent être prises en compte lors de l'ajout de stockage à un nœud ONTAP Select utilisant le RAID logiciel.

.ONTAP Select prend-il en charge les datastores de type vSAN ou de baie externe ?
ONTAP Select Deploy et ONTAP Select pour ESXi prennent en charge la configuration d'un cluster ONTAP Select à nœud unique utilisant soit un datastore de type vSAN, soit une baie externe comme pool de stockage.

ONTAP Select Deploy et ONTAP Select for KVM prennent en charge la configuration d'un cluster ONTAP Select à nœud unique utilisant un type de pool de stockage logique partagé sur des baies externes. Les pools de stockage peuvent être basés sur iSCSI ou FC/FCoE. Les autres types de pools de stockage ne sont pas pris en charge.

Les clusters haute disponibilité (HA) multi-nœuds sur stockage partagé sont pris en charge.

.ONTAP Select prend-il en charge les clusters multi-nœuds sur vSAN ou d'autres stockages externes partagés, y compris certaines piles HCI ?
Les clusters multi-nœuds utilisant un stockage externe (vNAS multi-nœuds) sont pris en charge pour ESXi et KVM. La combinaison de plusieurs hyperviseurs au sein d'un même cluster n'est pas prise en charge. Une architecture haute disponibilité sur stockage partagé implique toujours que chaque nœud d'une paire haute disponibilité possède une copie miroir des données de son partenaire. Cependant, un cluster multi-nœuds apporte les avantages des opérations sans interruption d'ONTAP, contrairement à un cluster mono-nœud qui repose sur VMware HA ou KVM Live Motion.

Bien que ONTAP Select Deploy ajoute la prise en charge de plusieurs machines virtuelles ONTAP Select sur le même hôte, il n'autorise pas ces instances à faire partie du même cluster ONTAP Select lors de la création du cluster. Pour les environnements ESXi, NetApp recommande de créer des règles d'anti-affinité pour les machines virtuelles afin que VMware HA n'essaie pas de migrer plusieurs machines virtuelles ONTAP Select du même cluster ONTAP Select vers un seul hôte ESXi. De plus, si ONTAP Select Deploy détecte qu'une vMotion administrative (initiée par l'utilisateur) ou une migration à chaud d'une machine virtuelle ONTAP Select a entraîné une violation de notre bonne pratique, comme la présence de deux nœuds ONTAP Select sur le même hôte physique, ONTAP Select Deploy affiche une alerte dans l'interface utilisateur Deploy et dans le journal. La seule façon pour ONTAP Select Deploy de connaître l'emplacement de la machine virtuelle ONTAP Select est à la suite d'une opération d'actualisation du cluster, qui est une opération manuelle que l'administrateur ONTAP Select Deploy doit initier. Il n'y a aucune fonctionnalité dans ONTAP Select Deploy permettant une surveillance proactive, et l'alerte n'est visible que via l'interface utilisateur Deploy ou le journal. En d'autres termes, cette alerte ne peut pas être transmise à une infrastructure de surveillance centralisée.

.Est-ce que ONTAP Select prend en charge NSX VXLAN de VMware ?
Les groupes de ports VXLAN NSX-V sont pris en charge. Pour la haute disponibilité multi-nœuds, y compris ONTAP MetroCluster SDS, assurez-vous de configurer la MTU du réseau interne entre 7500 et 8900 (au lieu de 9000) pour tenir compte de la surcharge VXLAN. La MTU du réseau interne peut être configurée avec ONTAP Select Deploy lors du déploiement du cluster.

.ONTAP Select prend-il en charge la migration à chaud KVM ?
Les machines virtuelles ONTAP Select exécutées sur des pools de stockage externes prennent en charge les migrations à chaud virsh.

.Ai-je besoin d'ONTAP Select Premium pour vSAN AF ?
Non, toutes les versions sont prises en charge, que la baie externe ou la configuration vSAN soit entièrement flash.

.Quels paramètres vSAN FTT/FTM sont pris en charge ?
La machine virtuelle Select hérite de la stratégie de stockage du datastore vSAN et aucune restriction ne s'applique aux paramètres FTT/FTM. Cependant, notez que, selon les paramètres FTT/FTM, la taille de la machine virtuelle ONTAP Select peut être nettement supérieure à la capacité configurée lors de son installation. ONTAP Select utilise des VMDK thick-eager, initialisés à zéro, qui sont créés lors de l'installation. Pour éviter d'affecter d'autres machines virtuelles utilisant le même datastore partagé, il est important de prévoir suffisamment de capacité libre dans le datastore pour accueillir la taille réelle de la machine virtuelle Select, telle que dérivée de la capacité Select et des paramètres FTT/FTM.

.Plusieurs nœuds ONTAP Select peuvent-ils fonctionner sur le même hôte s'ils font partie de clusters Select différents ?
Il est possible de configurer plusieurs nœuds ONTAP Select sur le même hôte uniquement pour les configurations vNAS, à condition que ces nœuds ne fassent pas partie du même cluster ONTAP Select. Cela n'est pas pris en charge pour les configurations DAS, car plusieurs nœuds ONTAP Select sur le même hôte physique entreraient en concurrence pour l'accès au contrôleur RAID.

.Pouvez-vous avoir un hôte avec un seul port 10GE exécutant ONTAP Select, et est-il disponible à la fois pour ESXi et KVM ?
Vous pouvez utiliser un seul port 10GE pour vous connecter au réseau externe. Cependant, NetApp recommande de n'utiliser cela que dans des environnements à petit facteur de forme et contraints. Ceci est pris en charge avec ESXi et KVM.

.Quelles sont les procédures supplémentaires à exécuter pour effectuer une migration à chaud sur KVM ?
Vous devez installer et exécuter les composants open source CLVM et pacemaker (pcs) sur chaque hôte participant à la migration à chaud. Ceci est nécessaire pour accéder aux mêmes groupes de volumes sur chaque hôte.



== vCenter

Il existe plusieurs questions et réponses concernant VMware vCenter.

.Comment ONTAP Select Deploy communique-t-il avec vCenter et quels ports de pare-feu doivent être ouverts ?
ONTAP Select Deploy utilise l'API VMware VIX pour communiquer avec le vCenter, l'hôte ESXi ou les deux. La documentation VMware indique que la connexion initiale à un vCenter Server ou à un hôte ESXi s'effectue via HTTPS/SOAP sur le port TCP 443. C'est le port pour le protocole HTTP sécurisé via TLS/SSL. Ensuite, une connexion à l'hôte ESXi est ouverte sur un socket du port TCP 902. Les données transitant par cette connexion sont chiffrées avec SSL. De plus, ONTAP Select Deploy émet une  `PING` commande pour vérifier qu'il y a un hôte ESXi répondant à l'adresse IP que vous avez spécifiée.

ONTAP Select Deploy doit également pouvoir communiquer avec les adresses IP de gestion des nœuds et du cluster ONTAP Select comme suit :

* Ping
* SSH (port 22)
* SSL (port 443)


Pour les clusters à deux nœuds, ONTAP Select Deploy héberge les boîtes aux lettres du cluster. Chaque nœud ONTAP Select doit pouvoir accéder à ONTAP Select Deploy via iSCSI (port 3260).

Pour les clusters multi-nœuds, le réseau interne doit être entièrement ouvert (pas de NAT ni de pare-feu).

.De quels droits vCenter ONTAP Select Deploy a-t-il besoin pour créer des clusters ONTAP Select ?
La liste des droits vCenter requis est disponible ici : link:reference_plan_ots_vcenter.html["Serveur VMware vCenter"].



== HA et clusters

Il existe plusieurs questions et réponses traitant des paires haute disponibilité et des clusters.

.Quelle est la différence entre un cluster à quatre nœuds, six nœuds ou huit nœuds et un cluster ONTAP Select à deux nœuds ?
Contrairement aux clusters à quatre, six et huit nœuds dans lesquels la machine virtuelle ONTAP Select Deploy est principalement utilisée pour créer le cluster, un cluster à deux nœuds dépend en permanence de la machine virtuelle ONTAP Select Deploy pour le quorum de haute disponibilité. Si la machine virtuelle ONTAP Select Deploy est indisponible, les services de basculement sont désactivés.

.Qu'est-ce que MetroCluster SDS ?
MetroCluster SDS est une option de réplication synchrone à moindre coût qui fait partie de la catégorie des solutions MetroCluster Business Continuity de NetApp. Elle est disponible uniquement avec ONTAP Select, contrairement à NetApp MetroCluster qui est disponible sur FAS Hybrid Flash, AFF et NetApp Private Storage for Cloud.

.En quoi la MetroCluster SDS est-elle différente de NetApp MetroCluster ?
MetroCluster SDS propose une solution de réplication synchrone et fait partie des solutions NetApp MetroCluster. Cependant, une différence majeure réside dans le type de connectivité (seuls les réseaux IP sont pris en charge plutôt que FC et IP).

.Quelle est la différence entre un cluster ONTAP Select à deux nœuds et un ONTAP MetroCluster SDS à deux nœuds ?
Un cluster à deux nœuds est défini comme un cluster dont les deux nœuds se trouvent dans le même centre de données, à moins de 300 m l'un de l'autre. En général, les deux nœuds sont connectés au même commutateur réseau ou à un ensemble de commutateurs réseau reliés par une liaison inter-commutateurs.

Le MetroCluster SDS à deux nœuds est défini comme un cluster dont les nœuds sont physiquement séparés (pièces différentes, bâtiments différents ou centres de données différents) et dont les connexions montantes de chaque nœud sont connectées à des commutateurs réseau distincts. Bien que MetroCluster SDS ne nécessite pas de matériel dédié, l’environnement doit respecter les exigences minimales de latence (5 ms RTT et 5 ms de gigue pour un total maximal de 10 ms).

MetroCluster SDS est une fonctionnalité premium nécessitant une licence Premium ou Premium XL. Une licence Premium prend en charge la création de machines virtuelles de petite et moyenne taille ainsi que l'utilisation de supports HDD et SSD. Toutes ces configurations sont prises en charge.

.La solution ONTAP MetroCluster SDS nécessite-t-elle un stockage local (DAS) ?
ONTAP MetroCluster SDS prend en charge tous les types de configurations de stockage (DAS et vNAS).

.ONTAP MetroCluster SDS prend-il en charge le RAID logiciel ?
Oui, le RAID logiciel est pris en charge avec les supports SSD sur KVM et ESXi.

.Est-ce que ONTAP MetroCluster SDS prend en charge à la fois les disques SSD et les disques durs à plateaux rotatifs ?
Oui, bien qu'une licence Premium soit requise, cette licence prend en charge les machines virtuelles de petite et moyenne taille ainsi que les SSD et les disques durs traditionnels.

.Est-ce que ONTAP MetroCluster SDS prend en charge les clusters de quatre nœuds et plus ?
Non, seuls les clusters à deux nœuds avec un médiateur peuvent être configurés en tant que MetroCluster SDS.

.Quelles sont les exigences pour ONTAP MetroCluster SDS ?
Les exigences sont les suivantes :

* Trois centres de données (un pour le ONTAP Select Deploy Mediator et un pour chaque nœud)
* 5 ms de RTT et 5 ms de gigue pour un total maximal de 10 ms
* 125 ms de RTT et une bande passante minimale de 5 Mbps entre le ONTAP Select Deploy Mediator et chaque nœud ONTAP Select
* Une licence Premium ou Premium XL


.ONTAP Select prend-il en charge vMotion ou VMware HA ?
Les machines virtuelles ONTAP Select exécutées sur des datastores vSAN ou des datastores de baies externes (en d'autres termes, des déploiements vNAS) prennent en charge vMotion, DRS et la fonctionnalité VMware HA.

.ONTAP Select prend-il en charge le stockage vMotion ?
Le stockage vMotion est pris en charge pour toutes les configurations, y compris les clusters ONTAP Select à nœud unique et à nœuds multiples, ainsi que la machine virtuelle ONTAP Select Deploy. Le stockage vMotion peut être utilisé pour migrer ONTAP Select ou la machine virtuelle ONTAP Select Deploy entre différentes versions de VMFS (par exemple, de VMFS 5 à VMFS 6), mais il n'est pas limité à ce cas d'utilisation. La bonne pratique consiste à arrêter la machine virtuelle avant d'initier une opération de stockage vMotion. ONTAP Select Deploy doit exécuter l'opération suivante après la fin de l'opération de stockage vMotion :

[listing]
----
cluster refresh
----

NOTE: Une opération de stockage vMotion entre différents types de banques de données n'est pas prise en charge. Autrement dit, les opérations de stockage vMotion entre des banques de données de type NFS et des banques de données VMFS ne sont pas prises en charge. De manière générale, les opérations de stockage vMotion entre des banques de données externes et des banques de données DAS ne sont pas prises en charge.

.Le trafic HA entre les nœuds ONTAP Select peut-il transiter par un vSwitch différent et/ou des ports physiques séparés et/ou en utilisant des câbles IP point à point entre les hôtes ESXi ?
Ces configurations ne sont pas prises en charge. ONTAP Select n'a pas accès à l'état des liaisons montantes du réseau physique transportant le trafic client. Par conséquent, ONTAP Select s'appuie sur le signal de présence HA pour garantir l'accessibilité de la machine virtuelle aux clients et à son homologue simultanément. En cas de perte de connectivité physique, l'absence de ce signal de présence HA entraîne un basculement automatique vers l'autre nœud, ce qui correspond au comportement attendu.

La séparation du trafic HA sur une infrastructure physique distincte peut permettre à une machine virtuelle Select de communiquer avec son homologue, mais pas avec ses clients. Ceci empêche le processus HA automatique et entraîne une indisponibilité des données jusqu'à ce qu'un basculement manuel soit déclenché.



== Service de médiation

Vous trouverez plusieurs questions et réponses concernant le service de médiation.

.Qu’est-ce que le service Mediator ?
Un cluster à deux nœuds s'appuie en permanence sur la machine virtuelle ONTAP Select Deploy pour le quorum de haute disponibilité. Une machine virtuelle ONTAP Select Deploy participant à une négociation de quorum de haute disponibilité à deux nœuds est qualifiée de Mediator VM.

.Le service Mediator peut-il être distant ?
Oui. ONTAP Select Deploy, agissant comme médiateur pour une paire haute disponibilité, prend en charge une latence WAN allant jusqu'à 500 ms RTT et nécessite une bande passante minimale de 5 Mbps.

.Quel protocole utilise le service Mediator ?
Le trafic du médiateur est de type iSCSI, provient des adresses IP de gestion des nœuds ONTAP Select et se termine sur l'adresse IP de déploiement ONTAP Select. Notez que vous ne pouvez pas utiliser IPv6 pour l'adresse IP de gestion des nœuds ONTAP Select lors de l'utilisation d'un cluster à deux nœuds.

.Puis-je utiliser un seul service Mediator pour plusieurs clusters HA à deux nœuds ?
Oui. Chaque machine virtuelle ONTAP Select Deploy peut servir de service de médiation commun pour un maximum de 100 clusters ONTAP Select à deux nœuds.

.Est-il possible de modifier l'emplacement du service Mediator après son déploiement ?
Oui. Il est possible d'utiliser une autre machine virtuelle ONTAP Select Deploy pour héberger le service Mediator.

.ONTAP Select prend-il en charge les clusters étendus avec (ou sans) le médiateur ?
Seul un cluster à deux nœuds avec un Mediator est pris en charge dans un modèle de déploiement HA étendu.
