---
sidebar: sidebar 
permalink: task_lic_acquire_cp.html 
keywords: license, licensing, acquire, Capacity Pools 
summary: 'Vous devez acquérir un fichier de licence pour chaque pool de capacité utilisé par les nœuds ONTAP Select. Le fichier de licence définit la capacité de stockage et la date d"expiration du pool. Il est verrouillé auprès du License Manager grâce à une combinaison du numéro de série unique de licence attribué par NetApp et de l"identifiant de verrouillage de licence associé à l"instance Deploy.' 
---
= Acquérir une licence ONTAP Select Capacity Pool
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Vous devez acquérir un fichier de licence pour chaque pool de capacité utilisé par les nœuds ONTAP Select. Le fichier de licence définit la capacité de stockage et la date d'expiration du pool. Il est verrouillé auprès du License Manager grâce à une combinaison du numéro de série unique de licence attribué par NetApp et de l'identifiant de verrouillage de licence associé à l'instance Deploy.

.Avant de commencer
* Vous devez disposer du numéro de série de licence à neuf chiffres attribué au pool de capacité par NetApp.
* Vous devez attendre au moins 24 heures après la date d'expédition de votre commande avant d'acquérir un fichier de licence.
* Vous avez examiné le link:sizing-capacity-pool-license.html["considérations relatives au dimensionnement d'une licence Capacity Pools"].


.À propos de cette tâche
Vous devez effectuer cette tâche pour chaque pool de capacité utilisé par les nœuds ONTAP Select.

.Étapes
. Connectez-vous au link:https://mysupport.netapp.com/site/["Site de support NetApp"^].
. Sélectionnez *Systems* > *Software Licenses*.
. Saisissez le numéro de série de la licence du pool de capacité et sélectionnez *Go!*.
. Sur la page des détails de la licence, accédez à la colonne *Détails du produit*.
. Sélectionnez *Get NetApp License File* sur la ligne appropriée.
. Saisissez l'ID de verrouillage de licence pour votre instance ONTAP Select Deploy et sélectionnez *Soumettre*.
. Sélectionnez le mode de livraison approprié et sélectionnez *Submit*.
. Sélectionnez *OK* sur la fenêtre de confirmation de livraison.


.Après avoir terminé
Vous devez télécharger le fichier de licence dans l'utilitaire d'administration Deploy avant qu'un nœud ONTAP Select puisse utiliser le pool de capacité.
